//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce__Mini_Proj_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        //public int CarItID { get; set; }
        //public Nullable<int> CartID { get; set; }
        //public Nullable<int> ProductID { get; set; }
        //public int Quantity { get; set; }
        //public decimal TtlPrice { get; set; }
        public int Id { get; set; } // Primary key
        public string Name { get; set; }
        public decimal Price { get; set; }

    }
}
